import { describe, it, expect } from 'vitest';
import app from '../src/app';

describe('P45 API Route Inventory', () => {
  it('should have all documented routes registered', async () => {
    const routes: Array<{ method: string; path: string }> = [];

    app.routes.forEach((route) => {
      routes.push({ method: route.method, path: route.path });
    });

    const publicRoutes = [
      { method: 'GET', path: '/health' },
      { method: 'GET', path: '/ready' },
      { method: 'GET', path: '/' },
      { method: 'POST', path: '/api/v1/auth/register' },
      { method: 'POST', path: '/api/v1/auth/login' },
      { method: 'POST', path: '/api/v1/auth/forgot-password' },
      { method: 'POST', path: '/api/v1/auth/reset-password' },
    ];

    const authenticatedRoutes = [
      { method: 'GET', path: '/api/v1/auth/me' },
      { method: 'POST', path: '/api/v1/auth/logout' },
      { method: 'POST', path: '/api/v1/auth/change-password' },
      { method: 'POST', path: '/api/v1/organizations' },
      { method: 'GET', path: '/api/v1/organizations/:id' },
      { method: 'PATCH', path: '/api/v1/organizations/:id' },
      { method: 'GET', path: '/api/v1/users' },
      { method: 'POST', path: '/api/v1/users' },
      { method: 'POST', path: '/api/v1/users/invite' },
      { method: 'GET', path: '/api/v1/users/:id' },
      { method: 'PATCH', path: '/api/v1/users/:id' },
      { method: 'POST', path: '/api/v1/users/:id/deactivate' },
      { method: 'POST', path: '/api/v1/sessions' },
      { method: 'GET', path: '/api/v1/sessions/:id' },
      { method: 'GET', path: '/api/v1/sessions/user/:userId' },
      { method: 'POST', path: '/api/v1/sessions/:id/revoke' },
      { method: 'POST', path: '/api/v1/sessions/user/:userId/revoke-all' },
      { method: 'POST', path: '/api/v1/sessions/revoke-all-others' },
      { method: 'GET', path: '/api/v1/contacts' },
      { method: 'POST', path: '/api/v1/contacts' },
      { method: 'GET', path: '/api/v1/contacts/:id' },
      { method: 'PATCH', path: '/api/v1/contacts/:id' },
      { method: 'DELETE', path: '/api/v1/contacts/:id' },
      { method: 'POST', path: '/api/v1/contacts/bulk/update' },
      { method: 'POST', path: '/api/v1/contacts/bulk/delete' },
      { method: 'GET', path: '/api/v1/companies' },
      { method: 'POST', path: '/api/v1/companies' },
      { method: 'GET', path: '/api/v1/companies/:id' },
      { method: 'PATCH', path: '/api/v1/companies/:id' },
      { method: 'DELETE', path: '/api/v1/companies/:id' },
      { method: 'POST', path: '/api/v1/companies/bulk/update' },
      { method: 'POST', path: '/api/v1/companies/bulk/delete' },
      { method: 'GET', path: '/api/v1/activities' },
      { method: 'POST', path: '/api/v1/activities' },
      { method: 'GET', path: '/api/v1/activities/:id' },
      { method: 'PATCH', path: '/api/v1/activities/:id' },
      { method: 'DELETE', path: '/api/v1/activities/:id' },
      { method: 'POST', path: '/api/v1/activities/bulk/delete' },
      { method: 'GET', path: '/api/v1/notes' },
      { method: 'POST', path: '/api/v1/notes' },
      { method: 'GET', path: '/api/v1/notes/:id' },
      { method: 'PATCH', path: '/api/v1/notes/:id' },
      { method: 'DELETE', path: '/api/v1/notes/:id' },
      { method: 'POST', path: '/api/v1/notes/bulk/delete' },
      { method: 'GET', path: '/api/v1/leads' },
      { method: 'POST', path: '/api/v1/leads' },
      { method: 'GET', path: '/api/v1/leads/:id' },
      { method: 'PATCH', path: '/api/v1/leads/:id' },
      { method: 'DELETE', path: '/api/v1/leads/:id' },
      { method: 'POST', path: '/api/v1/leads/bulk/delete' },
      { method: 'POST', path: '/api/v1/leads/:id/convert' },
      { method: 'GET', path: '/api/v1/pipelines' },
      { method: 'POST', path: '/api/v1/pipelines' },
      { method: 'GET', path: '/api/v1/pipelines/:id' },
      { method: 'PATCH', path: '/api/v1/pipelines/:id' },
      { method: 'DELETE', path: '/api/v1/pipelines/:id' },
      { method: 'POST', path: '/api/v1/pipelines/:id/stages' },
      { method: 'PATCH', path: '/api/v1/pipelines/:pipelineId/stages/:stageId' },
      { method: 'DELETE', path: '/api/v1/pipelines/:pipelineId/stages/:stageId' },
      { method: 'GET', path: '/api/v1/deals' },
      { method: 'POST', path: '/api/v1/deals' },
      { method: 'GET', path: '/api/v1/deals/:id' },
      { method: 'PATCH', path: '/api/v1/deals/:id' },
      { method: 'DELETE', path: '/api/v1/deals/:id' },
      { method: 'POST', path: '/api/v1/deals/:id/stage' },
      { method: 'POST', path: '/api/v1/deals/:id/won' },
      { method: 'POST', path: '/api/v1/deals/:id/lost' },
      { method: 'GET', path: '/api/v1/tasks' },
      { method: 'POST', path: '/api/v1/tasks' },
      { method: 'GET', path: '/api/v1/tasks/:id' },
      { method: 'PATCH', path: '/api/v1/tasks/:id' },
      { method: 'DELETE', path: '/api/v1/tasks/:id' },
      { method: 'POST', path: '/api/v1/tasks/:id/complete' },
      { method: 'GET', path: '/api/v1/notifications' },
      { method: 'GET', path: '/api/v1/notifications/unread-count' },
      { method: 'POST', path: '/api/v1/notifications/:id/read' },
      { method: 'POST', path: '/api/v1/notifications/read-all' },
      { method: 'GET', path: '/api/v1/search' },
      { method: 'GET', path: '/api/v1/imports' },
      { method: 'GET', path: '/api/v1/imports/:id' },
      { method: 'POST', path: '/api/v1/imports' },
      { method: 'POST', path: '/api/v1/imports/:id/preview' },
      { method: 'POST', path: '/api/v1/imports/:id/start' },
      { method: 'GET', path: '/api/v1/exports' },
      { method: 'GET', path: '/api/v1/exports/:id' },
      { method: 'GET', path: '/api/v1/exports/:id/download' },
      { method: 'POST', path: '/api/v1/exports' },
      { method: 'GET', path: '/api/v1/custom-fields' },
      { method: 'GET', path: '/api/v1/custom-fields/:id' },
      { method: 'POST', path: '/api/v1/custom-fields' },
      { method: 'PUT', path: '/api/v1/custom-fields/:id' },
      { method: 'DELETE', path: '/api/v1/custom-fields/:id' },
      { method: 'GET', path: '/api/v1/tags' },
      { method: 'GET', path: '/api/v1/tags/:id' },
      { method: 'POST', path: '/api/v1/tags' },
      { method: 'PUT', path: '/api/v1/tags/:id' },
      { method: 'DELETE', path: '/api/v1/tags/:id' },
      { method: 'GET', path: '/api/v1/dashboard/summary' },
      { method: 'GET', path: '/api/v1/dashboard/pipeline' },
      { method: 'GET', path: '/api/v1/reports/sales' },
      { method: 'GET', path: '/api/v1/reports/pipeline' },
      { method: 'GET', path: '/api/v1/reports/leads' },
      { method: 'GET', path: '/api/v1/reports/activity' },
      { method: 'POST', path: '/api/v1/reports/sales/export' },
      { method: 'GET', path: '/api/v1/reports/exports/:id' },
      { method: 'GET', path: '/api/v1/reports/exports/:id/download' },
      { method: 'GET', path: '/api/v1/api-keys' },
      { method: 'POST', path: '/api/v1/api-keys' },
      { method: 'POST', path: '/api/v1/api-keys/:id/revoke' },
      { method: 'GET', path: '/api/v1/webhooks' },
      { method: 'POST', path: '/api/v1/webhooks' },
      { method: 'PATCH', path: '/api/v1/webhooks/:id' },
      { method: 'DELETE', path: '/api/v1/webhooks/:id' },
      { method: 'GET', path: '/api/v1/webhooks/:id/deliveries' },
      { method: 'GET', path: '/api/v1/integrations' },
      { method: 'POST', path: '/api/v1/integrations/connect' },
      { method: 'PATCH', path: '/api/v1/integrations/:id' },
      { method: 'DELETE', path: '/api/v1/integrations/:id' },
      { method: 'POST', path: '/api/v1/integrations/:id/sync' },
    ];

    const allExpected = [...publicRoutes, ...authenticatedRoutes];

    for (const expected of allExpected) {
      const found = routes.some(
        (r) => r.method === expected.method && r.path === expected.path
      );
      expect(found, `Route ${expected.method} ${expected.path} should be registered`).toBe(true);
    }

    expect(routes.length).toBeGreaterThanOrEqual(allExpected.length);
  });
});
