import { getCollection } from './client';

export const collections = {
  organizations: () => getCollection<import('../types').OrganizationDocument>('organizations'),
  users: () => getCollection<import('../types').UserDocument>('users'),
  sessions: () => getCollection<import('../types').SessionDocument>('sessions'),
  roles: () => getCollection<import('../types').RoleDocument>('roles'),
  teams: () => getCollection<import('../types').TeamDocument>('teams'),
  contacts: () => getCollection<import('../types').ContactDocument>('contacts'),
  companies: () => getCollection<import('../types').CompanyDocument>('companies'),
  leads: () => getCollection<import('../types').LeadDocument>('leads'),
  pipelines: () => getCollection<import('../types').PipelineDocument>('pipelines'),
  pipelineStages: () => getCollection<import('../types').PipelineStageDocument>('pipeline_stages'),
  deals: () => getCollection<import('../types').DealDocument>('deals'),
  activities: () => getCollection<import('../types').ActivityDocument>('activities'),
  tasks: () => getCollection<import('../types').TaskDocument>('tasks'),
  notes: () => getCollection<import('../types').NoteDocument>('notes'),
  tags: () => getCollection<import('../types').TagDocument>('tags'),
  customFieldDefinitions: () => getCollection<import('../types').CustomFieldDefinitionDocument>('custom_field_definitions'),
  notifications: () => getCollection<import('../types').NotificationDocument>('notifications'),
  auditLogs: () => getCollection<import('../types').AuditLogDocument>('audit_logs'),
  attachments: () => getCollection<import('../types').AttachmentDocument>('attachments'),
  automations: () => getCollection<import('../types').AutomationDocument>('automations'),
  automationRuns: () => getCollection<import('../types').AutomationRunDocument>('automation_runs'),
  outboxEvents: () => getCollection<import('../types').OutboxEventDocument>('outbox_events'),
  importJobs: () => getCollection<import('../types').ImportJobDocument>('import_jobs'),
  exportJobs: () => getCollection<import('../types').ExportJobDocument>('export_jobs'),
  apiKeys: () => getCollection<import('../types').ApiKeyDocument>('api_keys'),
  webhooks: () => getCollection<import('../types').WebhookDocument>('webhooks'),
  webhookDeliveries: () => getCollection<import('../types').WebhookDeliveryDocument>('webhook_deliveries'),
  integrations: () => getCollection<import('../types').IntegrationDocument>('integrations'),
  passwordResetTokens: () => getCollection<import('../types').PasswordResetTokenDocument>('password_reset_tokens'),
  organizationMemberships: () => getCollection<import('../types').OrganizationMembershipDocument>('organization_memberships'),
  rolePermissions: () => getCollection<import('../types').RolePermissionDocument>('role_permissions'),
  rateLimits: () => getCollection<{ _id: string; count: number; resetAt: number }>('rate_limits'),
  files: () => getCollection<{ _id: string; content: Buffer; contentType: string; updatedAt: Date }>('files'),
};
